.PYTHON: seqstack1

seqstack1:
	g++ -o seqstack1 seqstack1.cpp -g

seqstack2:
	g++ -o seqstack2 seqstack2.cpp -g

seqstack3:
	g++ -o seqstack3 seqstack3.cpp -g

linkstack2:
	g++ -o linkstack2 linkstack2.cpp -g

clean:
	rm -rf seqstack1 linkstack2 seqstack2 seqstack3
